ignore:
    - "**/LecturerCoursesFragment.java"
    - "**/LecturerHomeFragment.java"
    - "**/LecturerAccountFragment.java"
    - "**/LecturerNavigation.java"
    - "**/StudentNavigation.java"
    - "**/StudentHomeFragment.java"
    - "**/StudentSubscriptionsFragment.java"
    - "**/StudentAccountFragment.java"
    - "**/StudentCoursePopUp.java"
    - "**/TopicResources.java"
    - "**/info_courses.java"
    - "**/Settings.java"
    - "**/ScrollLecturerCourse.java"
    - "**/UploadLectures.java"
    - "**/lecUploadPdf.java"
    - "**/SubbedCourseTopics.java"
    - "**/DisplayTopics.java"
    - "**/MainActivity.java"
    - "**/RegisterValidation.java"
    - "**/LoginValidation.java"
    - "**/TakeQuiz.java"
    - "**/CreateQuiz.java"
    - "**/Notification.java"
    - "**/QuizzesList.java"
    - "**/Rate.java"
    - "**/StudentTopicDashboard.java"
    - "**/displayQuizResults.java"
    - "**/LecturerResourceView.java"
